### PR TITLE
added directives for linux

### PR DESCRIPTION
**Pull request by GuvaCode**
I think that database need to load threads.
and create non-visual component TClamAv for easy use. the other day will do.

### CODE REVIEW

**Comment by reyjieroque** [comment]
I have not added threading, since what i have done is only testing the clamav3.pas working condition. It is up to the developer for (DELPHI/FPC) to venture into wider design. Maybe, some other time, we can design a clamav scanner comparable / better UI than clamwin :D :D written in FPC/DELPHI.

**Comment by GuvaCode** [comment]
good idea :) in no realtime ClamWin scanner. here you can use the driver.
http://www.delphisources.ru/pages/sources/system/2011-year/process-monitor.html

**Comment by GuvaCode** [comment]
hmm. cl_countsigs function always returns 11. or what I do not what you do.

**Comment by reyjieroque** [comment]
try the new sample app :D

**Pull request merged**
